name: Frontend CI

on:
  push:
    paths:
    - 'frontend/**'
  pull_request:
    paths:
    - 'frontend/**'

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install dependencies
      run: npm ci
      working-directory: frontend

    - name: Check formatting
      run: npm run prettier:check
      working-directory: frontend

  lint:
    needs: format
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install dependencies
      run: npm ci
      working-directory: frontend

    - name: Lint
      run: npm run lint
      working-directory: frontend